# Generated by Django 3.0.4 on 2020-04-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200411_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=24, verbose_name='学号/工号'),
        ),
    ]
