# Generated by Django 3.0.4 on 2020-05-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200428_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='telephone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentAddress',
            field=models.CharField(max_length=128, null=True, verbose_name='宿舍地址'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='brief',
            field=models.TextField(null=True, verbose_name='简介'),
        ),
    ]
