# Generated by Django 3.0.4 on 2020-05-09 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200501_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=24, unique=True, verbose_name='学号/工号'),
        ),
        migrations.AlterField(
            model_name='account',
            name='telephone',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=48, unique=True, verbose_name='班级姓名'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=24, unique=True, verbose_name='课程编号'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentClasses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Classes', verbose_name='班级'),
        ),
    ]
